# Generated by Django 5.1.2 on 2024-11-15 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('event_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('environment', models.CharField(max_length=255)),
                ('event_context', models.JSONField()),
                ('metadata_version', models.PositiveBigIntegerField(default=1)),
            ],
        ),
    ]
