# Generated by Django 5.1.2 on 2024-11-16 23:47

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('event_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('environment', models.CharField(max_length=255)),
                ('event_context', models.JSONField()),
                ('metadata_version', models.PositiveBigIntegerField(default=1)),
                ('retry_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[
                    ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('FAILED', 'Failed'),
                ], default='PENDING', max_length=20)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['event_date_time'],
                'indexes': [
                    models.Index(
                    fields=['event_date_time'],
                    name='event_outbo_event_d_9ea319_idx'), models.Index(fields=['event_type'],
                    name='event_outbo_event_t_1ceb76_idx'), models.Index(fields=['status'],
                    name='event_outbo_status_c29c0f_idx'),
                ],
            },
        ),
    ]
